"""LLM response models."""

from typing import Literal

from pydantic import BaseModel, Field


class LLMGeneratedQuery(BaseModel):
    """Query generated by LLM."""

    sql: str = Field(..., description="The generated SQL query")
    params: list[str] = Field(..., description="Parameter values for the query")
    tables_accessed: list[str] = Field(..., description="Tables accessed by the query")
    columns_returned: list[str] = Field(..., description="Columns in the SELECT clause")
    confidence: Literal["high", "medium", "low"] = Field(
        default="medium", description="Confidence level of the generation"
    )


class LLMMultiQueryResponse(BaseModel):
    """Response containing multiple queries."""

    queries: list[LLMGeneratedQuery]
    note: str | None = None


class LLMClarificationResponse(BaseModel):
    """Response when clarification is needed."""

    clarification_needed: Literal[True] = True
    message: str
    suggestions: list[str]


class LLMOutOfScopeResponse(BaseModel):
    """Response when request is out of scope."""

    out_of_scope: Literal[True] = True
    reason: str


# Union type for all possible LLM responses
LLMResponse = LLMGeneratedQuery | LLMMultiQueryResponse | LLMClarificationResponse | LLMOutOfScopeResponse
