"""
Domain models for the Clearing House system.
"""
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Optional
from datetime import datetime
from enum import Enum
import uuid


class TransactionStatus(Enum):
    """Status of a transaction in the clearing pipeline."""
    INGESTED = "ingested"
    VALIDATED = "validated"
    POSTED = "posted"
    REJECTED = "rejected"


@dataclass(frozen=True)
class Bank:
    """
    Represents a participant bank in the clearing system.

    Attributes:
        bank_id: Unique identifier for the bank
        name: Display name of the bank
        routing_number: Bank routing number (RTN) for US banks
        status: Whether the bank is active in the system
    """
    bank_id: str
    name: str
    routing_number: Optional[str] = None
    status: str = "active"

    def __str__(self) -> str:
        return self.name


@dataclass(frozen=True)
class Transaction:
    """
    Immutable transaction record representing a payment instruction.

    A transaction flows from payer (sender) to payee (receiver).
    Amount is always positive; direction is determined by payer/payee.

    Attributes:
        txn_id: Unique transaction identifier (for idempotency)
        payer: Bank ID of the sending bank
        payee: Bank ID of the receiving bank
        amount: Transaction amount (must be > 0)
        currency: ISO currency code (default USD)
        value_date: Settlement date
        ingest_ts: Timestamp when transaction was ingested
        status: Current status in the pipeline
    """
    payer: str
    payee: str
    amount: Decimal
    txn_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    currency: str = "USD"
    value_date: Optional[datetime] = None
    ingest_ts: datetime = field(default_factory=datetime.utcnow)
    status: TransactionStatus = TransactionStatus.INGESTED

    def __post_init__(self):
        if self.amount <= 0:
            raise ValueError(f"Transaction amount must be positive, got {self.amount}")
        if self.payer == self.payee:
            raise ValueError("Payer and payee cannot be the same bank")

    def __str__(self) -> str:
        return f"{self.payer} → {self.payee}: {self.amount} {self.currency}"


@dataclass(frozen=True)
class SettlementInstruction:
    """
    A settlement instruction generated by the netting engine.

    Represents the minimal money movement required after netting.

    Attributes:
        instruction_id: Unique identifier for the instruction
        payer: Bank that must pay
        payee: Bank that will receive
        amount: Settlement amount
        currency: ISO currency code
        batch_id: Reference to the settlement batch
        reference: Optional reference/memo
    """
    payer: str
    payee: str
    amount: Decimal
    instruction_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    currency: str = "USD"
    batch_id: Optional[str] = None
    reference: Optional[str] = None

    def __post_init__(self):
        if self.amount <= 0:
            raise ValueError(f"Settlement amount must be positive, got {self.amount}")
        if self.payer == self.payee:
            raise ValueError("Payer and payee cannot be the same bank")

    def __str__(self) -> str:
        return f"{self.payer} pays {self.payee}: {self.amount} {self.currency}"


@dataclass
class SettlementBatch:
    """
    A collection of settlement instructions for a cut-off period.

    Attributes:
        batch_id: Unique batch identifier
        currency: Currency for this batch
        cutoff_time: The cut-off timestamp for this batch
        source_transactions: List of transactions included in this batch
        net_positions: Net position per bank (positive = receive, negative = pay)
        instructions: Generated settlement instructions
        created_at: When the batch was created
    """
    batch_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    currency: str = "USD"
    cutoff_time: datetime = field(default_factory=datetime.utcnow)
    source_transactions: list = field(default_factory=list)
    net_positions: dict = field(default_factory=dict)
    instructions: list = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.utcnow)

    def add_transaction(self, txn: Transaction):
        """Add a transaction to this batch."""
        self.source_transactions.append(txn)

    def add_instruction(self, instruction: SettlementInstruction):
        """Add a settlement instruction to this batch."""
        self.instructions.append(instruction)

    def total_gross_volume(self) -> Decimal:
        """Calculate total gross volume of all transactions."""
        return sum(txn.amount for txn in self.source_transactions)

    def total_net_volume(self) -> Decimal:
        """Calculate total net volume of settlement instructions."""
        return sum(instr.amount for instr in self.instructions)

    def netting_efficiency(self) -> float:
        """
        Calculate netting efficiency as percentage reduction.
        Higher is better: 100% means no transfers needed.
        """
        gross = self.total_gross_volume()
        if gross == 0:
            return 100.0
        net = self.total_net_volume()
        return float((1 - net / gross) * 100)


# Type alias for pairwise balance key (alphabetically ordered bank pair)
PairwiseKey = tuple[str, str]

