package com.clearinghouse.model;

import java.math.BigDecimal;
import java.util.Objects;
import java.util.UUID;

/**
 * A settlement instruction generated by the netting engine.
 *
 * Represents the minimal money movement required after netting.
 */
public final class SettlementInstruction {
    private final String instructionId;
    private final String payer;
    private final String payee;
    private final BigDecimal amount;
    private final String currency;
    private final String batchId;

    public SettlementInstruction(String payer, String payee, BigDecimal amount) {
        this(UUID.randomUUID().toString(), payer, payee, amount, "USD", null);
    }

    public SettlementInstruction(String instructionId, String payer, String payee,
                                  BigDecimal amount, String currency, String batchId) {
        if (amount.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Settlement amount must be positive, got " + amount);
        }
        if (payer.equals(payee)) {
            throw new IllegalArgumentException("Payer and payee cannot be the same bank");
        }

        this.instructionId = instructionId;
        this.payer = Objects.requireNonNull(payer, "payer cannot be null");
        this.payee = Objects.requireNonNull(payee, "payee cannot be null");
        this.amount = Objects.requireNonNull(amount, "amount cannot be null");
        this.currency = Objects.requireNonNull(currency, "currency cannot be null");
        this.batchId = batchId;
    }

    public String getInstructionId() {
        return instructionId;
    }

    public String getPayer() {
        return payer;
    }

    public String getPayee() {
        return payee;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public String getCurrency() {
        return currency;
    }

    public String getBatchId() {
        return batchId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SettlementInstruction that = (SettlementInstruction) o;
        return Objects.equals(instructionId, that.instructionId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(instructionId);
    }

    @Override
    public String toString() {
        return payer + " pays " + payee + ": " + amount + " " + currency;
    }
}

